### ISSUE TITLE
why rebase from master by default?

### ISSUE THREAD

**Issue by samvloeberghs** [JakeWharton/rebaseandsqua.sh#4]
This is not to argue, but just to get an explanation :)
So why rebase from master by default? What if I consider my "dev" branch to be the main branch and "master" to be the release branch", for example

Grtz

**Comment by JakeWharton** [comment]
`master` probably covers 99.99% of repos. Since the HTML is static I don't have a way to specify other branches through a query param or subdomain or something.

**Comment by samvloeberghs** [comment]
alright, so I can just modify the script against "develop" branch to fulfil my needs. :+1: 
grtz!
